name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Linux ${{ matrix.build_type }}
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - RelWithDebInfo
          - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            ninja-build \
            clang-11 \
            gcc-9-multilib \
            g++-9-multilib \
            libstdc++-11-dev:i386

      - name: Configure
        run: |
          cmake \
            -S . \
            -B build/linux-${{ matrix.build_type }} \
            -G Ninja \
            -DCMAKE_C_COMPILER=/usr/bin/clang-11 \
            -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11 \
            -DCMAKE_C_FLAGS=-m32 \
            -DCMAKE_CXX_FLAGS=-m32 \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build/linux-${{ matrix.build_type }} --config ${{ matrix.build_type }} --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ matrix.build_type }}
          path: |
            build/linux-${{ matrix.build_type }}/**/*.so
          if-no-files-found: error

  windows:
    name: Windows ${{ matrix.build_type }}
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        build_type:
          - Debug
          - RelWithDebInfo
          - Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: |
          cmake `
            -S . `
            -B build/windows-${{ matrix.build_type }} `
            -A Win32 `
            -T ClangCL

      - name: Build
        run: cmake --build build/windows-${{ matrix.build_type }} --config ${{ matrix.build_type }} --parallel

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.build_type }}
          path: |
            build/windows-${{ matrix.build_type }}/${{ matrix.build_type }}/**/*.dll
          if-no-files-found: error
